//跨域代理前缀
const BASE_URL = process.env.NODE_ENV === 'development' ? '' : process.env.VUE_APP_API_BASE_URL

module.exports = {
    ROUTES: `${BASE_URL}/routes`,
    GET_RESET_PASSWORD: `${BASE_URL}/api/users/init-password`, // 登录 

    //// ### 自动生成的代码 #### ////
    AUTH_LOGIN: `${BASE_URL}/api/auth/login`, // 登录 
    CONFIG_OSS: `${BASE_URL}/api/config/oss`, // 获取OSS配置 
    EVENT: `${BASE_URL}/api/event/`, // 新增项目 
    EVENT_BASICS: `${BASE_URL}/api/event/basics`, // 项目基础信息 
    EVENT_DETAIL: `${BASE_URL}/api/event/detail`, // 项目基本信息 
    EVENT_PAGE: `${BASE_URL}/api/event/page`, // 项目列表分页 
    EVENT_UPDATE: `${BASE_URL}/api/event/update`, // 更新 
    EVENT_EXAMINE: `${BASE_URL}/api/event/examine`, // 审核 
    EVENT_OVER: `${BASE_URL}/api/event/over`, // 结束项目 
    EVENT_PROCESS: `${BASE_URL}/api/event/process`, // 项目进程 
    EVENT_PROCESS_AUDIT_PR: `${BASE_URL}/api/event/process/audit/pr`, // PR审核 
    EVENT_PROCESS_AUDIT_BUSINESS: `${BASE_URL}/api/event/process/audit/business`, // 商务审核 
    SKILLTAG_FIELDS: `${BASE_URL}/api/skillTag/fields`, // 获取领域标签 
    EVENT_IMPORT_PARAM: `${BASE_URL}/api/event/import/param`, // 导入外部名单(前端解析Excel) 
    EVENT_DUPLICATE: `${BASE_URL}/api/event/duplicate`, // 创建通告回显项目信息 
    EVENT_IMPORT_STATUS: `${BASE_URL}/api/event/import/status`, // 获取可导入的报名状态 
    EVENT_UPDATE_CREATOR: `${BASE_URL}/api/event/update/creator`, // 修改项目的创建者 
    ANNOUNCE_SAVE: `${BASE_URL}/api/announce/save`, // 创建/编辑通告 
    ANNOUNCE_END: `${BASE_URL}/api/announce/end`, // 下架通告 
    ANNOUNCE_RELATION: `${BASE_URL}/api/announce/relation`, // 关联通告 
    ANNOUNCE_CHECK: `${BASE_URL}/api/announce/check`, // 验收通告报名信息 
    ANNOUNCE_APPLY_REMARKS_SAVE: `${BASE_URL}/api/announce/apply/remarks/save`, // 通告报名备注编辑 
    ANNOUNCE_APPLY_REMARKS: `${BASE_URL}/api/announce/apply/remarks`, // 通告报名备注信息查询 
    ANNOUNCE_DEFINE_FIELDS: `${BASE_URL}/api/announce/define/fields`, // 查询通告数字类型自定义字段 
    ANNOUNCE_RELATION_OFFPRICE: `${BASE_URL}/api/announce/relation/offPrice/`, // 关联报价字段 
    ANNOUNCE_APPLY_FIELDS: `${BASE_URL}/api/announce/apply/fields`, // 获取报名的报价字段信息 
    ANNOUNCE_APPLY_CONFIRMOFFER: `${BASE_URL}/api/announce/apply/confirmOffer`, // 确认报价 
    ANNOUNCE_OFFFIELD: `${BASE_URL}/api/announce/offField`, // 报价字段查询 
    ANNOUNCE_PRICE_BATCHSAVE: `${BASE_URL}/api/announce/price/batchSave`, // 批量设置价格 
    ANNOUNCE_INFO: `${BASE_URL}/api/announce/info`, // 查看通告 
    ANNOUNCE_COMMONWORDS: `${BASE_URL}/api/announce/commonWords`, // 常用热词查询 
    ANNOUNCE_APPLY_SCREEN_STATUS: `${BASE_URL}/api/announce/apply/screen/status`, // 邀请协作人页面查询分配状态 
    ANNOUNCE_DEFINED_FIELDS: `${BASE_URL}/api/announce/defined/fields`, // 通告的自定义字段 
    ANNOUNCE_RELATION_OPTIONS: `${BASE_URL}/api/announce/relation/options`, // 获取关联通告下拉选择框选项集合 
    ANNOUNCE_BASIC_LIST: `${BASE_URL}/api/announce/basic/list`, // 根据项目id获取通告基本信息集合 
    ANNOUNCE_REGIONS: `${BASE_URL}/api/announce/regions`, // 获取项目探店城市回显 
    SETTLEMENT_ACCOUNT_PAGE: `${BASE_URL}/api/settlement/account/page`, // 结算管理达人列表分页查询 
    SETTLEMENT_DETAILLIST_PAGE: `${BASE_URL}/api/settlement/detaillist/page`, // 结算清单分页查询 
    SETTLEMENT_BATCH_ACCOUNT: `${BASE_URL}/api/settlement/batch/account`, // 批量达人结算 
    SETTLEMENT_CALLBACKURL_SAVE: `${BASE_URL}/api/settlement/callbackUrl/save`, // 保存回传链接 
    SETTLEMENT_DATA_SPIDER: `${BASE_URL}/api/settlement/data/spider`, // 批量更新数据 
    SETTLEMENT_EXECUTE_FAILED: `${BASE_URL}/api/settlement/execute/failed`, // 执行失败 
    SETTLEMENT_EXECUTE_RECOVER: `${BASE_URL}/api/settlement/execute/recover`, // 恢复执行 
    DEPT: `${BASE_URL}/api/dept`, // 部门列表 
    USERS: `${BASE_URL}/api/users`, // 账号列表 
    ROLES: `${BASE_URL}/api/roles`, // 角色列表 
    USERS_RELATION: `${BASE_URL}/api/users/relation`, // 查询用户的关联账号信息 
    USERS_UPDATEINFO: `${BASE_URL}/api/users/updateInfo`, // 修改账号信息 
    USERS_INIT_PASSWORD: `${BASE_URL}/api/users/init-password`, // 获取初始密码 
    AUTH_PUBLIC_KEY: `${BASE_URL}/api/auth/public-key`, // 获取公钥 
    NAMELIST_PRAE_PAGE: `${BASE_URL}/api/namelist/prae/page`, // PR/AE查询名单列表 
    APPLY_PROCESS_SCREEN_CONFIRM: `${BASE_URL}/api/apply/process/screen-confirm`, // 确认筛选名单 
    NAMELIST_BUSINESS_PAGE_1636959029320: `${BASE_URL}/api/namelist/business/page_1636959029320`, // 商务查询名单列表(入参以及返回以PR/AE接口为准)_copy 
    APPLY_PROCESS_CONFIRM_WORK: `${BASE_URL}/api/apply/process/confirm-work`, // 确认合作 
    NAMELIST_COOPERATOR: `${BASE_URL}/api/namelist/cooperator`, // 驳回协助人 
    NAMELIST_EXPORT_PAGE: `${BASE_URL}/api/namelist/export/page`, // 导出名单列表分页查询 
    STATISTICS_APPLY: `${BASE_URL}/api/statistics/apply`, // 查看通告名单统计信息 
    NAMELIST_PRICE_STATISTIC: `${BASE_URL}/api/namelist/price/statistic`, // 报名报价数据统计 
    NAMELIST_MARK: `${BASE_URL}/api/namelist/mark`, // 设置标记 
    APPLY_PROCESS_TALENT_REJECT_WORK: `${BASE_URL}/api/apply/process/talent-reject-work`, // 达人无法执行 
    NAMELIST_BUSINESS_PAGE: `${BASE_URL}/api/namelist/business/page`, // 商务查询名单列表(入参以及返回以PR/AE接口为准) 
    NAMELIST_ADMIN_PAGE: `${BASE_URL}/api/namelist/admin/page`, // 管理员查询名单列表(入参以及返回以PR/AE接口为准) 
    NAMELIST_TALENT_PAGE: `${BASE_URL}/api/namelist/talent/page`, // 待达人确认名单列表(入参以及返回以PR/AE接口为准) 
    NAMELIST_COOPERATOR_ADD: `${BASE_URL}/api/namelist/cooperator/add`, // 邀请协作人 
    NAMELIST_COOPERATOR_INFO: `${BASE_URL}/api/namelist/cooperator/info`, // 查看协作进度 
    APPLY_PROCESS_NOT_COOPERATION: `${BASE_URL}/api/apply/process/not-cooperation`, // 不合作 
    APPLY_PROCESS_BACKUP: `${BASE_URL}/api/apply/process/backup`, // 加入备选名单 
    APPLY_PROCESS_REMOVE_BACKUP: `${BASE_URL}/api/apply/process/remove-backup`, // 移出备选名单 
    APPLY_PROCESS_RESTORE_COOPERATION: `${BASE_URL}/api/apply/process/restore-cooperation`, // 恢复合作 
    APPLY_PROCESS_PR_PASS: `${BASE_URL}/api/apply/process/pr-pass`, // PR筛选通过 
    APPLY_PROCESS_PR_REJECT: `${BASE_URL}/api/apply/process/pr-reject`, // PR拒绝 
    APPLY_PROCESS_BUSINESS_PASS: `${BASE_URL}/api/apply/process/business-pass`, // 商务通过筛选 
    APPLY_PROCESS_BUSINESS_REJECT: `${BASE_URL}/api/apply/process/business-reject`, // 商务拒绝 
    APPLY_PROCESS_OWNER_PASS: `${BASE_URL}/api/apply/process/owner-pass`, // 甲方确认 
    ROLES_MENU: `${BASE_URL}/api/roles/menu`, // 权限设置 
    MENUS: `${BASE_URL}/api/menus`, // 菜单管理列表 
    ROLES_MENU_DEPRICATE: `${BASE_URL}/api/roles/menu_depricate`, // 获取菜单树集合(不用了) 
    MENUS_SUPERIOR: `${BASE_URL}/api/menus/superior`, //  修改信息回显 
    MENUS_LAZY: `${BASE_URL}/api/menus/lazy`, // 选择上级目录的信息查询接口 
    GENERAL_AREA: `${BASE_URL}/api/general/area`, // 查询区域信息  
    COMMON_WORDS: `${BASE_URL}/api/common/words`, // 获取个人的常用词库 
    COMMON_WORDS_UPDATESORT: `${BASE_URL}/api/common/words/updateSort`, // 个人常用词库排序 
    FIELD_LIST: `${BASE_URL}/api/field/list`, // 获取当前用户权限内能够看到的字段 
    FIELD_GROUP_LIST: `${BASE_URL}/api/field/group/list`, // 根据列表名获取当前用户相关字段展示配置 
    FIELD_ALL: `${BASE_URL}/api/field/all`, // 获取所有字段（新增或删除时选择父子段下拉框调用） 
    FIELD_GROUP_SAVE: `${BASE_URL}/api/field/group/save`, // 保存常用字段展示配置 
    ROLES_FIELD: `${BASE_URL}/api/roles/field`, // 新增角色字段 
    FIELD: `${BASE_URL}/api/field`, // 删除字段 
    FIELD_CATEGORY_UPDATE: `${BASE_URL}/api/field/category/update`, // 修改字段类别 
    FIELD_CATEGORY: `${BASE_URL}/api/field/category`, // 新增字段类别 
    FIELD_CATEGORY_LIST: `${BASE_URL}/api/field/category/list`, // 获取所有字段类别 
    FIELD_UPDATE: `${BASE_URL}/api/field/update`, // 修改字段 
    FIELD_PAGE: `${BASE_URL}/api/field/page`, // 分页查询字段 
    FIELD_TREE: `${BASE_URL}/api/field/tree`, // 获取字段树 
    FIELD_LIST_UPDATE: `${BASE_URL}/api/field/list/update`, // 修改字段列表 
    FIELD_LIST_ALL: `${BASE_URL}/api/field/list/all`, // 获取所有字段列表 
    //// ### 自动生成的代码 #### ////
}